create table app_user
(
    id       bigint generated by default as identity,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    surname  varchar(255),
    username varchar(255),
    primary key (id)
);
alter table app_user
    add constraint username unique (username);

create table user_authority
(
    id        bigint generated by default as identity,
    authority integer,
    user_id   bigint,
    primary key (id),
    foreign key (user_id)
        references app_user
);